spring:
  application:
    name: user
  cloud:
    nacos:
      discovery:
        server-addr: wsl2:8848
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
server:
  port: 8999
