spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: wsl2:8848
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: user

server:
  port: 8080
